### ISSUE TITLE
我在cmd中选择B，浏览器打开后是Not Found

### ISSUE THREAD

**Issue by digitalzhouhaowen** [MelohubAI/suno-ai-proxy#2]
你好，我选择B后浏览器打开后Not Found
![微信截图_20240328151933](https://github.com/kilingzhang/suno-ai-proxy/assets/25289500/baa648d2-15ce-4f56-8f96-e93b5159ca35)
![微信截图22_20240328152133](https://github.com/kilingzhang/suno-ai-proxy/assets/25289500/90b73aca-9e91-464e-8fab-e43f39d9b079)

**Comment by kilingzhang** [comment]
可以从postman文档里看一下接口路径，这里后续优化一下提示。

**Comment by digitalzhouhaowen** [comment]
> 可以从postman文档里看一下接口路径，这里后续优化一下提示。
请问一下 postman文档在哪查看

**Comment by digitalzhouhaowen** [comment]
> 可以从postman文档里看一下接口路径，这里后续优化一下提示。
请问一下 postman文档在哪查看

**Comment by kilingzhang** [comment]
> > 可以从postman文档里看一下接口路径，这里后续优化一下提示。
> > 请问一下 postman文档在哪查看

README
