### ISSUE TITLE
有详细的部署流程吗？谢谢

### ISSUE THREAD

**Issue by chadyi** [MelohubAI/suno-ai-proxy#3]
有详细的部署流程吗？谢谢

**Comment by kilingzhang** [comment]
> 有详细的部署流程吗？谢谢

本地部署吗？还是部署到cloudflare上？

**Comment by kilingzhang** [comment]
> > 有详细的部署流程吗？谢谢
> 
> 本地部署吗？还是部署到cloudflare上？

晚点维护一下部署文档

**Comment by chadyi** [comment]
本地部署，centos8服务器

**Comment by kilingzhang** [comment]
> 本地部署，centos8服务器

不好意思，最近有点忙。目前本地是只支持开发模式。本身是基于 cloudflare page开发的。没有单独适配。可以注册个账号白嫖额度。如果实在想在服务器部署，可以按照开发模式开启。但是不太推荐。
